# Copyright Hyperledger Aries contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger:
  - master

pr:
  - master

jobs:
   - job: buildDockerUbu

    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: Bash@3
        displayName: docker compose
        inputs:
          targetType: 'filePath'
          filePath: ci/docker-compose-test.sh
