# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: projectversionasvariable@1
  inputs:
    path: 'Directory.Build.props'
    
- task: MSBuild@1
  inputs:
    solution: 'src/Hyperledger.Aries.sln'
    msbuildArguments: '/t:pack /p:Version=$(Version.MajorMinorPatch)-preview.$(Build.BuildId) /p:Configuration=Release /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/pre'
- task: MSBuild@1
  inputs:
    solution: 'src/Hyperledger.Aries.sln'
    msbuildArguments: '/t:pack /p:Version=$(Version.MajorMinorPatch) /p:Configuration=Release /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/release'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'