version: '3'
services:
  indy-pool:
    build:
      context: .
      dockerfile: docker/indy-pool.dockerfile
      args:
        pool_ip: 10.0.0.10
    ports:
      - "9701-9709:9701-9709"
    networks:
      agent_net:
        ipv4_address: 10.0.0.10

  web-agent-1:
    build:
      context: .
      dockerfile: docker/web-agent.dockerfile
    environment:
      - ASPNETCORE_URLS=http://10.0.0.11:7000
      - ASPNETCORE_ENVIRONMENT=Development
      - ENDPOINT_HOST=${HOST1:-http://10.0.0.11:7000}
    ports:
      - "7000:7000"
    depends_on:
      - "indy-pool"
    links:
      - "indy-pool"
    networks:
      agent_net:
        ipv4_address: 10.0.0.11

  web-agent-2:
    build:
      context: .
      dockerfile: docker/web-agent.dockerfile
    environment:
      - ASPNETCORE_URLS=http://10.0.0.12:8000
      - ASPNETCORE_ENVIRONMENT=Development
      - ENDPOINT_HOST=${HOST2:-http://10.0.0.12:8000}
    ports:
      - "8000:8000"
    depends_on:
      - "indy-pool"
    links:
      - "indy-pool"
    networks:
      agent_net:
        ipv4_address: 10.0.0.12
    
networks:
  agent_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16