# Copyright Hyperledger contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master

pr: none

jobs:
  - job: VerifyBuild

    pool:
        vmImage: 'ubuntu-18.04'

    variables:
        buildConfiguration: 'Release'

    steps:
        - checkout: self
        - script: docker-compose --verbose -f docker-compose.test.yaml up --build --abort-on-container-exit --exit-code-from test-agent
          displayName: "Docker"
